config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_service.urls', namespace='mailing_service')),
    path('users/', include('users.urls', namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (UserCreateView, UserDetailView, UserListView,
                         UserLoginView, UserPasswordResetCompleteView,
                         UserPasswordResetConfirmView,
                         UserPasswordResetDoneView, UserPasswordResetView,
                         blocked_users, email_verification, unblocked_users, UserUpdateView)

# from . import views


app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(template_name='login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),

    path('reset_password/', UserPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', UserPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('users/', UserListView.as_view(), name='users'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='detail_user'),
    path('users/update<int:pk>/', UserUpdateView.as_view(), name='update_user'),
    path('users/blocked/<int:pk>/', blocked_users, name="blocked_user"),
    path('users/unblocked/<int:pk>/', unblocked_users, name="unblocked_user"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    avatar = models.ImageField(upload_to='users/avatars/', blank=True, null=True, verbose_name="Аватар",
                               help_text='Загрузите свой аватар')
    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True,
                             help_text='Введите номер телефона')
    country = models.CharField(max_length=20, verbose_name='Страна', blank=True, null=True,
                               help_text='Введите свою страну')
    token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)
    is_blocked = models.BooleanField(default=False, help_text="Пользователь заблокирован?")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ("can_view_users_list", "Может просматривать список пользователей"),
            ("can_block_users", "Может блокировать пользователей"),
            ("can_unblock_users", "Может разблокировать пользователей"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    '''Форма для регистрации пользователя'''
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    """Форма для авторизации (Валидация при блокировке аккаунта)"""
    username = forms.EmailField(label="Email")

    def confirm_login_allowed(self, user):
        if user.is_blocked:
            raise forms.ValidationError(
                "Аккаунт заблокирован.",
                code="blocked"
            )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'avatar', 'phone', 'country']

users/views.py
import secrets

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import (LoginView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic import (CreateView, DetailView, ListView, UpdateView)

from config import settings
from users.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject='Подтверждение почты',
            message=f"Здравствуйте, перейдите по ссылки для подтверждения почты {url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    context_object_name = 'user'
    template_name = "users/user_update.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        # Редирект на detail_user с pk текущего пользователя
        return reverse("users:detail_user", kwargs={"pk": self.object.pk})


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = "users/login.html"


class UserListView(ListView):
    model = User
    context_object_name = 'account_user'
    template_name = 'users/users_list.html'
    permission_required = 'users.can_view_users_list'


class UserDetailView(DetailView):
    model = User
    context_object_name = 'account_user'
    template_name = 'users/user_detail.html'
    permission_required = 'users.can_view_users_list'


@login_required
@permission_required('users.can_block_users', raise_exception=True)
def blocked_users(request, pk):
    """Блокировка пользователя (для менеджера)"""
    user = get_object_or_404(User, pk=pk)
    user.is_blocked = True
    user.save()
    return redirect(reverse('users:detail_user', kwargs={'pk': user.pk}))


@login_required
@permission_required('users.can_unblock_users', raise_exception=True)
def unblocked_users(request, pk):
    """Разблокировка пользователя (для менеджера)"""
    user = get_object_or_404(User, pk=pk)
    user.is_blocked = False
    user.save()
    return redirect(reverse('users:detail_user', kwargs={'pk': user.pk}))


class UserPasswordResetView(PasswordResetView):
    '''Класс позволяет пользователю сбросить пароль, сгенерировав одноразовую ссылку,
    которую можно использовать для сброса пароля,
    и отправив эту ссылку на зарегистрированный адрес электронной почты пользователя.'''
    email_template_name = "users/password_reset_email.html"  # письмо, которое придет на почту
    success_url = reverse_lazy("users:password_reset_done")
    template_name = "users/password_reset_form.html"


class UserPasswordResetDoneView(PasswordResetDoneView):
    '''Подтверждение отправки сообщения с инструкцией на почту '''
    template_name = "users/password_reset_done.html"


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """Подтверждение cмены пароля"""
    success_url = reverse_lazy("users:password_reset_complete")
    template_name = "users/password_reset_confirm.html"


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    """Информация о смене пароля"""
    template_name = "users/password_reset_complete.html"
    success_url = reverse_lazy("users:login")

users/templates/users/login.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Авторизация пользователя{% endblock %}

{% block inner_content%}
<h3 class="display-6">Авторизация пользователя</h3>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row text-start" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-start">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-secondary my-1">
                        Авторизоваться
                    </button>
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Смена пароля{% endblock %}

{% block inner_content%}
<p>Пароль для пользователя успешно сменен</p>
<a href="{% url 'users:login' %}" class="btn btn-light btn-lg mt-3">Войти</a>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Смена пароля{% endblock %}

{% block inner_content%}
<h1>Смена пароля</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row text-start" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-start">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-secondary my-1">
                        Подтвердить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Смена пароля{% endblock %}

{% block inner_content%}
<div class="container">
        <h1 class="mt-4">Запрос на сброс пароля отправлен</h1>
        <p>Мы отправили вам инструкции по сбросу пароля на указанный email.</p>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
Восстановление пароля для пользователя {{ user.get_email }}. Перейдите по следующей ссылке:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
Если вы не запрашивали сброс пароля, проигнорируйте это письмо.
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Восстановление пароля{% endblock %}

{% block inner_content%}
<h3 class="display-6">Восстановление пароля</h3>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row text-start" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-start">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-secondary my-1">
                       Отправить
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Пользователь{% endblock %}

{% block inner_content%}
<h3 class="display-6">Пользователь</h3>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-body text-center w-auto">
                    {% if not account_user.is_superuser %}
                    <h5 class="card-title text-start">Пользователь: {{ account_user.email }}</h5>
                        <p class="card-text text-start">Телефон: {{ account_user.phone }}</p></p>
                        <p class="card-text text-start">Страна: {{ account_user.country }} </p>
                        <p class="card-text text-start">Статус активности: {% if account_user.is_active %}
                        <span class="badge bg-success">Активен
                        </span>
                        {% else %}
                        <span class="badge bg-danger">Неактивен</span>
                        {% endif %}</p>
                        <p class="card-text text-start">Статус блокировки: {% if not account_user.is_blocked %}
                        <span class="badge bg-success">Не заблокирован
                        </span>
                        {% else %}
                        <span class="badge bg-danger">Заблокирован</span>
                        {% endif %}</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <div class="btn-group-vertical">
                            <a class="btn btn-outline-secondary " href="{% url 'users:users' %}"
                               role="button">Вернуться
                                к списку пользователей</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Регистрация пользователя{% endblock %}

{% block inner_content%}
<h3 class="display-6">Регистрация пользователя</h3>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row text-start" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-start">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-secondary my-1">
                       Зарегистрироваться
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_update.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Редактирование профиля{% endblock %}

{% block inner_content%}
<h3 class="display-6">Редактирование профиля</h3>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row text-start" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-start">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-outline-secondary">Сохранить</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/users_list.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление пользователями{% endblock %}

{% block inner_content%}
<h3 class="display-6">Список пользователей</h3>
<p class="lead text-white-50">Управление пользователями</p>
{% if perms.users.can_view_users_list or user.is_superuser %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>Телефон</th>
                    <th>Страна</th>
                    <th>Статус активности</th>
                    <th>Статус блокировки</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for user in account_user %}
                {% if not user.is_superuser %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.phone }}</td>
                    <td>{{ user.country }}</td>
                    <td>
                        {% if user.is_active %}
                        <span class="badge bg-success">Активен</span>
                        {% else %}
                        <span class="badge bg-danger">Неактивен</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if not user.is_blocked %}
                        <span class="badge bg-success">Не заблокирован</span>
                        {% else %}
                        <span class="badge bg-danger">Заблокирован</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'users:detail_user' user.pk %}"  class="btn btn-sm btn-light">
                            Просмотр
                        </a>

                        <!-- Кнопка блокировки (если пользователь не заблокирован) -->
                        {% if not user.is_blocked and perms.users.can_block_users %}
                        <form method="post" action="{% url 'users:blocked_user' user.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    Заблокировать
                                </button>
                                </form>
                        {% endif %}
                        {% if user.is_blocked and perms.users.can_unblock_users %}
                        <form method="post" action="{% url 'users:unblocked_user' user.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">
                                    Разблокировать
                                </button>
                                </form>
                        {% endif %}
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}