config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_service.urls', namespace='mailing_service')),
    path('users/', include('users.urls', namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_service.apps import MailingServiceConfig
from mailing_service.views import (
    HomePageView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingMessageCreateView,
    MailingMessageDeleteView,
    MailingMessageDetailView,
    MailingMessageListView,
    MailingMessageUpdateView,
    MailingRecipientCreateView,
    MailingRecipientDeleteView,
    MailingRecipientDetailView,
    MailingRecipientListView,
    MailingRecipientUpdateView,
    MailingSendView,
    MailingUpdateView,
    disable_mailing,
    mailing_report,
)

# from . import views


app_name = MailingServiceConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path(
        "clients/", cache_page(60)(MailingRecipientListView.as_view()), name="clients"
    ),
    path("clients/create/", MailingRecipientCreateView.as_view(), name="create_client"),
    path(
        "clients/<int:pk>/",
        cache_page(60)(MailingRecipientDetailView.as_view()),
        name="detail_client",
    ),
    path(
        "clients/update/<int:pk>/",
        MailingRecipientUpdateView.as_view(),
        name="update_client",
    ),
    path(
        "clients/delete/<int:pk>/",
        MailingRecipientDeleteView.as_view(),
        name="delete_client",
    ),
    path(
        "messages/", cache_page(60)(MailingMessageListView.as_view()), name="messages"
    ),
    path("messages/create/", MailingMessageCreateView.as_view(), name="create_message"),
    path(
        "messages/<int:pk>/",
        cache_page(60)(MailingMessageDetailView.as_view()),
        name="detail_message",
    ),
    path(
        "messages/update/<int:pk>/",
        MailingMessageUpdateView.as_view(),
        name="update_message",
    ),
    path(
        "messages/delete/<int:pk>/",
        MailingMessageDeleteView.as_view(),
        name="delete_message",
    ),
    path("mailings/", MailingListView.as_view(), name="mailings"),
    path("mailings/create/", MailingCreateView.as_view(), name="create_mailing"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="detail_mailing"),
    path(
        "mailings/update/<int:pk>/", MailingUpdateView.as_view(), name="update_mailing"
    ),
    path(
        "mailings/delete/<int:pk>/", MailingDeleteView.as_view(), name="delete_mailing"
    ),
    path("mailings/send/<int:pk>/", MailingSendView.as_view(), name="send_mailing"),
    path("attempts/", mailing_report, name="attempts"),
    path("mailings/disable/<int:pk>/", disable_mailing, name="disable_mailing"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (UserCreateView, UserDetailView, UserListView,
                         UserLoginView, UserPasswordResetCompleteView,
                         UserPasswordResetConfirmView,
                         UserPasswordResetDoneView, UserPasswordResetView,
                         blocked_users, email_verification, unblocked_users, UserUpdateView)

# from . import views


app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(template_name='login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),

    path('reset_password/', UserPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', UserPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('users/', UserListView.as_view(), name='users'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='detail_user'),
    path('users/update<int:pk>/', UserUpdateView.as_view(), name='update_user'),
    path('users/blocked/<int:pk>/', blocked_users, name="blocked_user"),
    path('users/unblocked/<int:pk>/', unblocked_users, name="unblocked_user"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/models.py
from django.db import models
from django.utils import timezone

from users.models import User

# Create your models here.


class MailingRecipient(models.Model):
    name = models.CharField(max_length=250, verbose_name="Ф.И.О.")
    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий")
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Владелец", null=True, blank=True
    )

    def __str__(self):
        return f"{self.name} - {self.email}"

    class Meta:
        verbose_name = "получатель рассылки"
        verbose_name_plural = "получатели рассылки"
        ordering = [
            "name",
        ]
        permissions = [("can_view_all_recipients", "Может просматривать всех клиентов")]


class MailingMessage(models.Model):
    subject = models.CharField(max_length=250, verbose_name="Тема письма")
    message = models.TextField(verbose_name="Письмо")
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Владелец", null=True, blank=True
    )

    def __str__(self):
        return f"{self.subject} - {self.message}"

    class Meta:
        verbose_name = "Cooбщение"
        verbose_name_plural = "Сообщения"
        ordering = [
            "subject",
        ]
        permissions = [("can_view_all_messages", "Может просматривать все сообщения")]


class Mailing(models.Model):
    CREATED = "created"
    LAUNCHED = "launched"
    COMPLETED = "completed"

    MAILING_STATUS = [
        (CREATED, "Создана"),
        (LAUNCHED, "Запущена"),
        (COMPLETED, "Завершена"),
    ]
    start_time = models.DateTimeField(verbose_name="Дата и время начала отправки")
    end_time = models.DateTimeField(verbose_name="Дата и время окончания отправки")
    status = models.CharField(
        max_length=12,
        choices=MAILING_STATUS,
        default=CREATED,
        verbose_name="Статус рассылки",
    )
    message = models.ForeignKey(
        MailingMessage,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Сообщение",
    )
    recipients = models.ManyToManyField(
        MailingRecipient, blank=True, verbose_name="Получатели"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания рассылки"
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Владелец", null=True, blank=True
    )

    def update_status(self):
        """Метод для определения статуса рассылки на основе текущего времени"""
        time_now = timezone.now()
        new_status = self.status

        if time_now < self.start_time:
            new_status = self.CREATED

        elif time_now >= self.end_time:
            new_status = self.COMPLETED

        elif self.start_time <= time_now < self.end_time:
            new_status = self.LAUNCHED

        if self.status != new_status:
            self.status = new_status
            self.save()

        return new_status

    def __str__(self):
        return f"Рассылка создана {self.created_at}, статус: {self.status}"

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        ordering = [
            "status",
        ]
        permissions = [
            ("can_view_all_mailings", "Может просматривать все рассылки"),
            ("can_disable_mailing", "Может отключать рассылки"),
        ]

    def recipients_list(self):
        """Возвращает строку с получателями для админки"""
        return ", ".join([str(recipient) for recipient in self.recipients.all()[:3]])

    recipients_list.short_description = "Получатели"

    def recipients_count(self):
        """Возвращает количество получателей"""
        return self.recipients.count()

    recipients_count.short_description = "Кол-во получателей"


class AttemptSendMailing(models.Model):
    SUCCESSFUL = "successful"
    FAILED = "failed"

    SEND_MAILING_STATUS = [
        (SUCCESSFUL, "Успешно"),
        (FAILED, "Не успешно"),
    ]
    attempt_time = models.DateTimeField(
        verbose_name="Дата и время начала попытки рассылки"
    )
    status = models.CharField(
        max_length=12,
        choices=SEND_MAILING_STATUS,
        verbose_name="Статус попытки рассылки",
    )
    server_response = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка"
    )
    recipient = models.ForeignKey(
        MailingRecipient, on_delete=models.CASCADE, verbose_name="Получатель"
    )

    def __str__(self):
        return (
            f"{self.mailing}, {self.recipient}: {self.status} - {self.server_response}"
        )

    class Meta:
        verbose_name = "попытка рассылки"
        verbose_name_plural = "попытки рассылок"
        ordering = [
            "status",
        ]

mailing_service/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils import timezone

from mailing_service.models import Mailing, MailingMessage, MailingRecipient


class MailingRecipientForm(ModelForm):
    class Meta:
        model = MailingRecipient
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(MailingRecipientForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Введите имя получателя",
            }
        )

        self.fields["email"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Введите email получателя",
            }
        )

        self.fields["comment"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not (
            email.endswith("@gmail.com")
            or email.endswith("@yandex.ru")
            or email.endswith("@mail.ru")
        ):
            raise ValidationError(
                "Email должен оканчиваться на @gmail.com, @yandex.ru или @mail.ru"
            )
        return email


class MailingMessageForm(ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(MailingMessageForm, self).__init__(*args, **kwargs)

        self.fields["subject"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Введите тему письма",
            }
        )

        self.fields["message"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Введите текст письма",
            }
        )


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        exclude = ("created_at", "status", "owner")
        widgets = {
            "start_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "message": forms.Select(
                attrs={"class": "form-select", "style": "width: 100%;"}
            ),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)  # получаем пользователя из kwargs
        super(MailingForm, self).__init__(*args, **kwargs)

        self.fields["start_time"].required = True
        self.fields["end_time"].required = True

        self.fields["start_time"].widget.attrs.update(
            {
                "class": "form-control",
                "type": "datetime-local",
            }
        )

        self.fields["end_time"].widget.attrs.update(
            {
                "class": "form-control",
                "type": "datetime-local",
            }
        )

        self.fields["message"].widget.attrs.update(
            {
                "class": "form-control",
                "size": "5",
            }
        )

        self.fields["recipients"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

        # фильтруем данные для текущего пользователя
        if self.user:
            # Для суперпользователя показываем все
            if self.user.is_superuser:
                self.fields["message"].queryset = MailingMessage.objects.all()
                self.fields["recipients"].queryset = MailingRecipient.objects.all()
            else:
                # Для обычного пользователя - только данные, для которых он является влаельцем
                self.fields["message"].queryset = MailingMessage.objects.filter(
                    owner=self.user
                )
                self.fields["recipients"].queryset = MailingRecipient.objects.filter(
                    owner=self.user
                )

    def clean_start_time(self):
        """Валидация даты и времени начала отправки (не может быть в прошлом, раньше end_time)"""
        start_time = self.cleaned_data.get("start_time")
        time_now = timezone.now()

        if not start_time:
            raise ValidationError("Укажите дату и время начала отправки")

        if start_time:
            if start_time < time_now:
                raise ValidationError(
                    "Дата и время начала отправки не может быть в прошлом"
                )
        return start_time

    def clean_end_time(self):
        """Валидация даты и времени начала отправки (не может быть в прошлом, раньше end_time)"""
        end_time = self.cleaned_data.get("end_time")
        time_now = timezone.now()

        if not end_time:
            raise ValidationError("Укажите дату и время окончания отправки")

        if end_time < time_now:
            raise ValidationError(
                "Дата и время окончания отправки не может быть в прошлом"
            )
        return end_time

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if start_time and end_time:
            if start_time >= end_time:
                self.add_error(
                    "start_time",
                    "Дата и время начала отправки не может быть позже даты и времени окончания отправки",
                )

mailing_service/templates/mailing_service/base_inner.html
{% extends 'mailing_service/base.html' %}

{% block body_class %}d-flex flex-column min-vh-100 text-bg-secondary{% endblock %}

{% block content %}
<main class="container mt-5 pt-4 text-center">
    {% block inner_content %}
    {% endblock %}
</main>
{% endblock %}

mailing_service/templates/mailing_service/mailing_confirm_delete.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление рассылками{% endblock %}

{% block inner_content%}
<h3 class="display-6">Удаление рассылки</h3>
<p class="lead text-white-50">Управление базой рассылок</p>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body text-center w-auto">
                        <p class="card-text text-center"> Вы действительно хотите удалить рассылку</p>
                        <p class="card-text text-center"> "Cтатус рассылки: {{ mailing.get_status_display }} - {{mailing.message|truncatechars:100 }}, получатели: {{mailing.recipients}}"?</p>
                        <div class="card-body">
                            {% csrf_token %}
                        </div>
                        <div class="d-flex justify-content-center align-items-center">
                            <div class="btn-group-vertical">
                                <a class="btn btn-outline-secondary"
                                   href="{% url 'mailing_service:detail_mailing' mailing.pk %}"
                                   role="button">Перейти к рассылке</a>
                                <a class="btn btn-outline-secondary " href="{% url 'mailing_service:mailings' %}"
                                   role="button">Вернуться к списку рассылок</a>
                                <button type="submit" class="btn btn-outline-danger">
                                    Удалить
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

mailing_service/templates/mailing_service/mailing_detail.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление рассылками{% endblock %}

{% block inner_content%}
<h3 class="display-6">Рассылка</h3>
<p class="lead text-white-50">Управление базой рассылок</p>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-body text-center w-auto">
                    <h5 class="card-title text-start">Cтатус рассылки: {{ mailing.get_status_display }}</h5>
                        <p class="card-text text-start">Сообщение:<p class="text-start mb-auto"> {{mailing.message }}</p></p>
                        <p class="card-text text-start">Получатели:
                            {% for client in mailing.recipients.all %}
                             <p class="text-start mb-auto"> {{client.name}}</p>
                            {% endfor %}
                        </p>
                        <p class="card-text text-start">Дата создания: {{mailing.created_at|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Дата первой отправки: {{mailing.start_time|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Дата окончания отправки: {{mailing.end_time|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Владелец: {{ mailing.owner.email }}</p>
                        {% if mailing.status == 'created' %}
                        <p class="card-text text-start">Рассылка не может быть отправлена, запланированное время отправки не наступило</p>
                        {% endif %}
                    <div class="d-flex justify-content-center align-items-center">
                        <div class="btn-group-vertical">
                            <a class="btn btn-outline-secondary " href="{% url 'mailing_service:mailings' %}"
                               role="button">Вернуться
                                к списку рассылок</a>
                            {% if user == mailing.owner or user.is_superuser %}
                            <div class="btn-group" role="group">

                                <button type="button" class="btn btn-secondary dropdown-toggle"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    Редактировать
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'mailing_service:update_mailing' mailing.pk %}" role="button">Изменить</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'mailing_service:delete_mailing' mailing.pk %}" role="button">Удалить</a>
                                    </li>
                                </ul>
                            </div>
                            {% endif %}
                            {% if mailing.status == 'launched' and perms.mailing_service.can_disable_mailing or user.is_superuser %}
                                <form method="post" action="{% url 'mailing_service:disable_mailing' mailing.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    Отключить
                                </button>
                                </form>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing_service/templates/mailing_service/mailing_list.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление рассылками{% endblock %}

{% block inner_content%}
<h3 class="display-6">Рассылки</h3>
<p class="lead text-white-50">Управление базой рассылок</p>
{% if not user|in_group:'Менеджеры' %}
<div class="text-center">
    <p>
        <a class="btn btn-light" href="{% url 'mailing_service:create_mailing' %}" role="button">Создать рассылку</a>
    </p>
</div>
{% endif %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for mailing in mailings %}
            {% if user == mailing.owner or perms.mailing_service.can_view_all_mailings or user.is_superuser %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body mb-auto">
                        <h5 class="card-title text-start">Cтатус рассылки: {{ mailing.get_status_display }}</h5>
                        <p class="card-text text-start">Сообщение:
                        <p class="text-start mb-auto"> {{mailing.message|truncatechars:100 }}</p></p>
                        <p class="card-text text-start">Получатели:
                            {% for client in mailing.recipients.all %}
                            <p class="text-start mb-auto"> {{client.name}}</p>
                            {% endfor %}
                        </p>
                        <p class="card-text text-start">Дата создания: {{mailing.created_at|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Дата первой отправки: {{mailing.start_time|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Дата окончания отправки: {{mailing.end_time|date:"d M Y H:i" }}</p>
                        <p class="card-text text-start">Владелец: {{ mailing.owner.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group-vertical text-center">
                                <a class="btn btn-outline-secondary btn-sm"
                                   href="{% url 'mailing_service:detail_mailing' mailing.pk %}"
                                   role="button">Подробнее</a>
                                {% if user == mailing.owner or user.is_superuser %}
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn btn-outline-secondary dropdown-toggle btn-sm"
                                            data-bs-toggle="dropdown" aria-expanded="false">
                                        Редактировать
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item"
                                               href="{% url 'mailing_service:update_mailing' mailing.pk %}"
                                               role="button">Изменить</a></li>
                                        <li><a class="dropdown-item"
                                               href="{% url 'mailing_service:delete_mailing' mailing.pk %}"
                                               role="button">Удалить</a></li>
                                    </ul>
                                </div>
                                {% endif %}
                                {% if mailing.status == 'launched' and perms.mailing_service.can_disable_mailing or user.is_superuser %}
                                <form method="post" action="{% url 'mailing_service:disable_mailing' mailing.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    Отключить
                                </button>
                                </form>
                                {% endif %}
                            </div>
                            {% if mailing.status == 'created'%}
                            <form method="post" action="{% url 'mailing_service:send_mailing' mailing.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">
                                    Отправить
                                </button>
                            </form>
                            {% endif %}
                            {% if mailing.status == 'launched' %}
                            <form method="post" action="{% url 'mailing_service:send_mailing' mailing.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">
                                    Отправить повторно
                                </button>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
            {% endif %}
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mailing_recipient_detail.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление клиентами{% endblock %}

{% block inner_content%}
<h3 class="display-6">Клиент</h3>
<p class="lead text-white-50">Управление базой клиентов для рассылок</p>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-body text-center w-auto">
                    <h5 class="card-title"> ФИО: {{ client.name }}</h5>
                    <p class="card-text "> Электронная почта: {{ client.email }}</p>
                    <p class="card-text "> Комментарий: {{ client.comment }}</p>
                    <p class="card-text "> Владелец: {{ client.owner.email }}</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <div class="btn-group-vertical">
                            <a class="btn btn-outline-secondary " href="{% url 'mailing_service:clients' %}"
                               role="button">Вернуться
                                к списку клиентов</a>
                            {% if user == client.owner or user.is_superuser %}
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-secondary dropdown-toggle"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    Редактировать
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'mailing_service:update_client' client.pk %}" role="button">Изменить</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'mailing_service:delete_client' client.pk %}" role="button">Удалить</a>
                                    </li>
                                </ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing_service/templates/mailing_service/mailing_recipient_list.html
{% extends 'mailing_service/base_inner.html' %}
{% load my_tags %}

{% block title %}Управление клиентами{% endblock %}

{% block inner_content%}
<h3 class="display-6">Список клиентов</h3>
<p class="lead text-white-50">Управление базой клиентов для рассылок</p>
{% if not user|in_group:'Менеджеры' %}
<div class="text-center">
    <p>
        <a class="btn btn-light" href="{% url 'mailing_service:create_client' %}" role="button">Добавить нового
            клиента</a>
    </p>
</div>
{% endif %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <ul class="list-group list-group-numbered">
                {% for client in clients %}
                    {% if user == client.owner or perms.mailing_service.can_view_all_recipients or user.is_superuser %}
                <li class="list-group-item d-flex justify-content-between align-items-start">

                    <div class="ms-2 me-auto">
                        <div>{{client.name}}</div>
                    </div>
                    <a class="btn btn-outline-secondary btn-sm"
                       href="{% url 'mailing_service:detail_client' client.pk %}" role="button">Подробнее</a>

                    {% if user == client.owner or user.is_superuser %}
                    <div class="ms-2 btn-group" role="group">
                        <button type="button" class="btn btn-outline-secondary dropdown-toggle btn-sm"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            Редактировать
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'mailing_service:update_client' client.pk %}"
                                   role="button">Изменить</a></li>
                            <li><a class="dropdown-item" href="{% url 'mailing_service:delete_client' client.pk %}"
                                   role="button">Удалить</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </li>
                {% endif %}
                {% endfor %}

            </ul>
        </div>
    </div>
</div>
{% endblock %}